### PR TITLE
Fix webassest

### PR DESCRIPTION
**Pull request by steveoni**
This pr fixe some webassets issues: such as not identifying the URL path for the CSS path and some js unknown errors.

removing `cssrewrite` and `rsjmin` and adding `IConfigurable` to the plugin seems to fix these issues.

if this pr is decided to be merged, it might be good to test on all platforms `dataexplorer-react` is being used to prevent any breakage.

@sagargg @sagargg-zz

### CODE REVIEW

**Comment by sagargg** [comment]
@steveoni  do we still need this fix? updating build files didn't work?

**Comment by steveoni** [comment]
@sagargg updating the build fix the error in ok involving searching for source map..  but the error involving not locating the css added to web assets was not fixed..

so I discovered that removing cssrewrite and rjsmin and adding the configurable to plugin fix it... 


but the branch can be left alone without merging.. I think it might be that ckan environment having issues

**Comment by anuveyatsu** [comment]
Is this PR compatible with both v2.8 and v2.9?

**Comment by anuveyatsu** [comment]
Hi @steveoni can we get this updated and merged so that we mainly support 2.9 and 2.10?

**Comment by steveoni** [comment]
@anuveyatsu just to be clear, you don't want us to support a lower version again? cause we already have support for >= 2.9 and < 2.9

**Pull request merged**
